// src/components/pages/Login/index.tsx
import React, { useState } from "react";

import { Button, Card, Form, Input, Layout, Typography } from "antd";

import Box from "../../atoms/Box";
import LoginBg from "../../../assets/login_bg.jpg";
import { LoginPayload } from "../../../domain/auth/types";
import useLogin from "../../../domain/auth/useLogin";
import { AxiosError, isAxiosError } from "axios";

const { Title, Text } = Typography;
const { Content } = Layout;

const Login = () => {
  const login = useLogin();
  const [authError, setAuthError] = useState("");

  const onFinish = (values: LoginPayload) => {
    setAuthError("");
    login.mutate(values, {
      onError: (error) => {
        if (isAxiosError(error)) {
          setAuthError(error.response?.data.message);
        } else {
          setAuthError("Ocorreu um erro, tente novamente");
        }
      },
    });
  };

  return (
    <Layout
      style={{
        width: "100vw",
        height: "100vh",
        display: "flex",
        flexDirection: "row",
      }}
    >
      <Box
        params={{
          flexBasis: "60%",
          background: `#ffffff url(${LoginBg}) no-repeat center center`,
          backgroundSize: "cover",
        }}
      ></Box>
      <Content style={{ padding: "0 50px" }}>
        <Box
          params={{
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            height: "100%",
          }}
        >
          <Title style={{ textAlign: "center" }} italic level={2}>
            #WEGOGYM
          </Title>
          <Card>
            <Form
              requiredMark={false}
              layout="vertical"
              initialValues={{ remember: true }}
              onFinish={onFinish}
            >
              <Form.Item
                name="email"
                label="Email"
                rules={[
                  { required: true, message: "Insira seu email!" },
                  { type: "email", message: "Email inválido!" },
                ]}
              >
                <Input />
              </Form.Item>
              <Form.Item
                label="Senha"
                name="password"
                rules={[{ required: true, message: "Insira sua senha!" }]}
              >
                <Input type="password" />
              </Form.Item>

              <Text type="danger">{authError}</Text>
              <Form.Item>
                <Button
                  loading={login.isLoading}
                  type="primary"
                  htmlType="submit"
                >
                  Entrar
                </Button>
              </Form.Item>
            </Form>
          </Card>
        </Box>
      </Content>
    </Layout>
  );
};

export default Login;

// src/components/pages/Login.vue
<script setup lang="ts">
import { isAxiosError } from "axios";
import { reactive, ref } from "vue";

import { TextField } from "../";
import { validationRules } from "@/utils/validationRules";
import useLogin from "@/domain/auth/useLogin";

const login = useLogin();
const form = reactive({ email: "", password: "" });
const formError = ref("");

const onSubmit = () => {
  formError.value = "";
  login.mutate(form, {
    onError: (error: any) => {
      if (isAxiosError(error)) {
        formError.value = error.response?.data.message;
      } else {
        formError.value = "Ocorreu um erro, tente novamente";
      }
    },
  });
};
</script>

<template>
  <div class="login-container__form">
    <v-form @submit.prevent="onSubmit">
      <v-container>
        <h1 class="my-6 text-center"><i>#WEGOGYM</i></h1>
        <text-field
          class="mb-3"
          type="email"
          label="E-mail"
          :rules="[validationRules.required, validationRules.email]"
          v-model="form.email"
        />
        <text-field
          type="password"
          label="Senha"
          :rules="[validationRules.required]"
          v-model="form.password"
        />

        <v-btn
          block
          :loading="login.isLoading.value"
          color="primary"
          size="large"
          type="submit"
          variant="elevated"
        >
          Entrar
        </v-btn>
        <p class="text-center mt-4 text-red font-weight-bold" v-if="formError">
          {{ formError }}
        </p>
      </v-container>
    </v-form>
  </div>
</template>

<style lang="scss" scoped>
.login-container {
  width: 100vw;
  height: 100vh;
  overflow: hidden;
  display: flex;
  &__img {
    flex-basis: 60%;
    background: #ffffff url("@/assets/imgs/login_bg.jpg") no-repeat center
      center;
    background-size: cover;
  }
  &__form {
    flex: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    .v-form {
      width: 100%;
    }
    .v-container {
      max-width: 500px;
    }
  }
}
</style>
